spring:
  data:
    redis:
      host: localhost
      port: 6379
      password: null
      lettuce:
        pool:
          max-active: 8 #最大连接数
          max-idle: 8   #最大空闲等待数
          min-idle: 1   #最小空闲等待数
          max-wait: 100 #连接等待时间
      database: 0 #使用0号数据库